### ISSUE TITLE
Uncaught exception 

### ISSUE THREAD

**Issue by J-CMartin** [zachowj/xfinity-data-usage#108]
Even if the data usage update has been rare and random, the Container would keep running until stopped. After upgrading to the latest version, it ran for 48 hours before throwing the exception below:

`
      2023-04-19 09:29:21 [error] : Error: State did not change for 3 tries. Last state: NotLoggedIn. Next update at 10:29:07 AM
      node:internal/process/promises:288
                  triggerUncaughtException(err, true /* fromPromise */);
                  ^
      page.goto: Navigation failed because page was closed!
      =========================== logs ===========================
      navigating to "https://customer.xfinity.com/#/devices#usage", waiting until "load"
      ============================================================
          at #startOver (file:///home/node/app/dist/xfinity.js:103:20)
          at Xfinity.fetch (file:///home/node/app/dist/xfinity.js:78:40)
          at async Timeout.fetch [as _onTimeout] (file:///home/node/app/dist/app.js:41:22) {
        name: 'Error'
      }
 
      Node.js v18.16.0`

During this 48 hr run, it was able to retrieve the data usage 4 times.

**Comment by zachowj** [comment]
In the latest build running on a VM with no docker, I had one error that was correctly caught and no crashes over a 24-hour period.

<details><summary>Details</summary>
<p>

2023-04-22 00:15:11 [info] : Usage updated: 606 GB. Next update at 12:34:46 AM
2023-04-22 00:35:18 [info] : Usage updated: 606 GB. Next update at 12:54:46 AM
2023-04-22 00:55:11 [info] : Usage updated: 606 GB. Next update at 1:14:46 AM
2023-04-22 01:15:13 [info] : Usage updated: 607 GB. Next update at 1:34:46 AM
2023-04-22 01:35:12 [info] : Usage updated: 607 GB. Next update at 1:54:46 AM
2023-04-22 01:55:13 [info] : Usage updated: 607 GB. Next update at 2:14:46 AM
2023-04-22 02:15:16 [info] : Usage updated: 608 GB. Next update at 2:34:46 AM
2023-04-22 02:35:11 [info] : Usage updated: 608 GB. Next update at 2:54:46 AM
2023-04-22 02:55:14 [info] : Usage updated: 608 GB. Next update at 3:14:46 AM
2023-04-22 03:15:12 [info] : Usage updated: 608 GB. Next update at 3:34:46 AM
2023-04-22 03:35:09 [info] : Usage updated: 608 GB. Next update at 3:54:46 AM
2023-04-22 03:55:12 [info] : Usage updated: 608 GB. Next update at 4:14:46 AM
2023-04-22 04:15:10 [info] : Usage updated: 608 GB. Next update at 4:34:46 AM
2023-04-22 04:35:10 [info] : Usage updated: 608 GB. Next update at 4:54:46 AM
2023-04-22 04:55:10 [info] : Usage updated: 608 GB. Next update at 5:14:46 AM
2023-04-22 05:15:10 [info] : Usage updated: 609 GB. Next update at 5:34:46 AM
2023-04-22 05:35:11 [info] : Usage updated: 609 GB. Next update at 5:54:46 AM
2023-04-22 05:55:07 [info] : Usage updated: 609 GB. Next update at 6:14:46 AM
2023-04-22 06:15:15 [info] : Usage updated: 610 GB. Next update at 6:34:46 AM
2023-04-22 06:35:10 [info] : Usage updated: 610 GB. Next update at 6:54:46 AM
2023-04-22 06:55:12 [info] : Usage updated: 610 GB. Next update at 7:14:46 AM
2023-04-22 07:15:15 [info] : Usage updated: 611 GB. Next update at 7:34:46 AM
2023-04-22 07:35:15 [info] : Usage updated: 611 GB. Next update at 7:54:46 AM
2023-04-22 07:55:10 [info] : Usage updated: 611 GB. Next update at 8:14:46 AM
2023-04-22 08:15:18 [info] : Usage updated: 612 GB. Next update at 8:34:46 AM
2023-04-22 08:35:14 [info] : Usage updated: 612 GB. Next update at 8:54:46 AM
2023-04-22 08:55:10 [info] : Usage updated: 612 GB. Next update at 9:14:46 AM
2023-04-22 09:15:16 [info] : Usage updated: 612 GB. Next update at 9:34:46 AM
2023-04-22 09:35:12 [info] : Usage updated: 612 GB. Next update at 9:54:46 AM
2023-04-22 09:55:12 [info] : Usage updated: 612 GB. Next update at 10:14:46 AM
2023-04-22 10:15:12 [info] : Usage updated: 613 GB. Next update at 10:34:46 AM
2023-04-22 10:35:09 [info] : Usage updated: 613 GB. Next update at 10:54:46 AM
2023-04-22 10:55:16 [info] : Usage updated: 613 GB. Next update at 11:14:46 AM
2023-04-22 11:15:13 [info] : Usage updated: 613 GB. Next update at 11:34:46 AM
2023-04-22 11:35:21 [info] : Usage updated: 613 GB. Next update at 11:54:46 AM
2023-04-22 11:55:14 [info] : Usage updated: 613 GB. Next update at 12:14:46 PM
2023-04-22 12:15:13 [info] : Usage updated: 613 GB. Next update at 12:34:46 PM
2023-04-22 12:35:14 [info] : Usage updated: 613 GB. Next update at 12:54:46 PM
2023-04-22 12:55:10 [info] : Usage updated: 613 GB. Next update at 1:14:46 PM
2023-04-22 13:15:18 [info] : Usage updated: 613 GB. Next update at 1:34:46 PM
2023-04-22 13:35:18 [info] : Usage updated: 613 GB. Next update at 1:54:46 PM
2023-04-22 13:55:16 [info] : Usage updated: 613 GB. Next update at 2:14:46 PM
2023-04-22 14:15:26 [info] : Usage updated: 613 GB. Next update at 2:34:46 PM
2023-04-22 14:35:10 [info] : Usage updated: 613 GB. Next update at 2:54:46 PM
2023-04-22 14:55:13 [info] : Usage updated: 613 GB. Next update at 3:14:46 PM
2023-04-22 15:15:13 [info] : Usage updated: 613 GB. Next update at 3:34:46 PM
2023-04-22 15:35:22 [info] : Usage updated: 613 GB. Next update at 3:54:46 PM
2023-04-22 15:55:21 [info] : Usage updated: 613 GB. Next update at 4:14:46 PM
2023-04-22 16:15:23 [info] : Usage updated: 615 GB. Next update at 4:34:46 PM
2023-04-22 16:35:22 [info] : Usage updated: 615 GB. Next update at 4:54:46 PM
2023-04-22 16:55:23 [info] : Usage updated: 615 GB. Next update at 5:14:46 PM
2023-04-22 17:15:13 [info] : Usage updated: 617 GB. Next update at 5:34:46 PM
2023-04-22 17:35:15 [info] : Usage updated: 617 GB. Next update at 5:54:46 PM
2023-04-22 17:56:14 [info] : Usage updated: 617 GB. Next update at 6:14:46 PM
2023-04-22 18:15:35 [info] : Usage updated: 617 GB. Next update at 6:34:46 PM
2023-04-22 18:35:25 [info] : Usage updated: 617 GB. Next update at 6:54:46 PM
2023-04-22 18:55:16 [info] : Usage updated: 617 GB. Next update at 7:14:46 PM
2023-04-22 19:16:05 [error] : TimeoutError: page.waitForLoadState: Timeout 60000ms exceeded.
=========================== logs ===========================
  "domcontentloaded" event fired
  "load" event fired
============================================================. Next update at 7:34:46 PM
2023-04-22 19:35:13 [info] : Usage updated: 618 GB. Next update at 7:54:46 PM
2023-04-22 19:55:25 [info] : Usage updated: 618 GB. Next update at 8:14:46 PM
2023-04-22 20:15:42 [info] : Usage updated: 619 GB. Next update at 8:34:46 PM
2023-04-22 20:35:26 [info] : Usage updated: 619 GB. Next update at 8:54:46 PM
2023-04-22 20:55:21 [info] : Usage updated: 619 GB. Next update at 9:14:46 PM
2023-04-22 21:15:16 [info] : Usage updated: 620 GB. Next update at 9:34:46 PM
2023-04-22 21:35:20 [info] : Usage updated: 620 GB. Next update at 9:54:46 PM
2023-04-22 21:55:13 [info] : Usage updated: 620 GB. Next update at 10:14:46 PM
2023-04-22 22:15:16 [info] : Usage updated: 626 GB. Next update at 10:34:46 PM
2023-04-22 22:35:17 [info] : Usage updated: 626 GB. Next update at 10:54:46 PM
2023-04-22 22:55:17 [info] : Usage updated: 626 GB. Next update at 11:14:46 PM
2023-04-22 23:15:26 [info] : Usage updated: 629 GB. Next update at 11:34:46 PM
2023-04-22 23:35:13 [info] : Usage updated: 629 GB. Next update at 11:54:46 PM
2023-04-22 23:55:17 [info] : Usage updated: 629 GB. Next update at 12:14:46 AM
2023-04-23 00:15:15 [info] : Usage updated: 631 GB. Next update at 12:34:46 AM
2023-04-23 00:35:13 [info] : Usage updated: 631 GB. Next update at 12:54:46 AM
2023-04-23 00:55:15 [info] : Usage updated: 631 GB. Next update at 1:14:46 AM


</p>
</details>
