### ISSUE TITLE
TimeoutError: waiting for selector `#passwd` failed: timeout 30000ms exceeded

### ISSUE THREAD

**Issue by janssenjones** [zachowj/xfinity-data-usage#58]
I'm wondering if anyone has successfully authenticated recently.  Mine's been broken for weeks, and it appears others have also posted issues, though I didn't see any responses or fixes on others' issues, and other issues have been closed.   I'm really just wondering if I need to attempt to troubleshoot/fix, or if it's just known to be broken at this point.

xfinity    | 2022-07-13 10:23:55 [verbose] : Fetching Data
xfinity    | 2022-07-13 10:23:55 [debug] : Loading (https://customer.xfinity.com)
xfinity    | 2022-07-13 10:23:55 [info] : Connected to MQTT
xfinity    | 2022-07-13 10:23:57 [debug] : Login redirects: 3
xfinity    | 2022-07-13 10:23:57 [debug] : Logging in
xfinity    | 2022-07-13 10:24:00 [debug] : Page Title: Sign in to Xfinity
xfinity    | 2022-07-13 10:24:00 [debug] : Loading Usage https://customer.xfinity.com/apis/csp/account/me/services/internet/usage?filter=internet
xfinity    | 2022-07-13 10:24:01 [debug] : Not logged in
xfinity    | 2022-07-13 10:24:01 [debug] : Loading (https://customer.xfinity.com)
xfinity    | 2022-07-13 10:24:03 [debug] : Login redirects: 3
xfinity    | 2022-07-13 10:24:03 [debug] : Logging in
xfinity    | 2022-07-13 10:24:35 [error] : TimeoutError: waiting for selector `#passwd` failed: timeout 30000ms exceeded. Next update at 11:23:55 AM

**Comment by mrulrich1** [comment]
You might need to change your frequency to >60 mins. I'm getting the same timeout error sometimes but there's also cases where it will update. see my logs below

`2022-07-02 14:53:41 [error] : Error: net::ERR_NAME_NOT_RESOLVED at https://customer.xfinity.com. Next update at 10:53:21 PM,
2022-07-02 22:53:56 [error] : TimeoutError: waiting for selector `#passwd` failed: timeout 30000ms exceeded. Next update at 6:53:21 AM,
2022-07-03 06:53:33 [info] : Usage updated: 24 GB. Next update at 2:53:21 PM,
2022-07-03 14:53:33 [info] : Usage updated: 26 GB. Next update at 10:53:21 PM,
2022-07-03 22:53:56 [error] : TimeoutError: waiting for selector `#passwd` failed: timeout 30000ms exceeded. Next update at 6:53:21 AM,
2022-07-04 06:53:34 [info] : Usage updated: 31 GB. Next update at 2:53:21 PM,
2022-07-04 14:53:33 [info] : Usage updated: 32 GB. Next update at 10:53:21 PM,
2022-07-04 22:53:34 [info] : Usage updated: 34 GB. Next update at 6:53:21 AM,
2022-07-05 06:53:41 [info] : Usage updated: 36 GB. Next update at 2:53:21 PM,
2022-07-05 14:53:33 [info] : Usage updated: 39 GB. Next update at 10:53:21 PM,
2022-07-05 22:53:35 [info] : Usage updated: 60 GB. Next update at 6:53:21 AM,
2022-07-06 06:53:34 [info] : Usage updated: 63 GB. Next update at 2:53:21 PM,
2022-07-06 14:53:58 [error] : TimeoutError: waiting for selector `#passwd` failed: timeout 30000ms exceeded. Next update at 10:53:21 PM,
2022-07-06 22:53:33 [info] : Usage updated: 115 GB. Next update at 6:53:21 AM,
2022-07-07 06:53:38 [info] : Usage updated: 118 GB. Next update at 2:53:21 PM,
2022-07-07 14:53:57 [error] : TimeoutError: waiting for selector `#passwd` failed: timeout 30000ms exceeded. Next update at 10:53:21 PM,
2022-07-07 22:53:34 [info] : Usage updated: 124 GB. Next update at 6:53:21 AM,
2022-07-08 06:53:34 [info] : Usage updated: 127 GB. Next update at 2:53:21 PM,
2022-07-08 14:53:57 [error] : TimeoutError: waiting for selector `#passwd` failed: timeout 30000ms exceeded. Next update at 10:53:21 PM,
2022-07-08 22:53:58 [error] : TimeoutError: waiting for selector `#passwd` failed: timeout 30000ms exceeded. Next update at 6:53:21 AM,
2022-07-09 06:53:57 [error] : TimeoutError: waiting for selector `#passwd` failed: timeout 30000ms exceeded. Next update at 2:53:22 PM,
2022-07-09 14:53:57 [error] : TimeoutError: waiting for selector `#passwd` failed: timeout 30000ms exceeded. Next update at 10:53:22 PM,
2022-07-09 22:53:38 [info] : Usage updated: 169 GB. Next update at 6:53:22 AM,
2022-07-10 06:53:34 [info] : Usage updated: 173 GB. Next update at 2:53:22 PM,
2022-07-10 14:53:35 [info] : Usage updated: 200 GB. Next update at 10:53:22 PM,
2022-07-10 22:53:35 [info] : Usage updated: 224 GB. Next update at 6:53:22 AM,
2022-07-11 06:53:43 [info] : Usage updated: 228 GB. Next update at 2:53:22 PM,
2022-07-11 14:53:34 [info] : Usage updated: 259 GB. Next update at 10:53:22 PM,
2022-07-11 22:53:34 [info] : Usage updated: 282 GB. Next update at 6:53:22 AM,
2022-07-12 06:53:44 [error] : Error: Unable to login. Next update at 2:53:22 PM,
2022-07-12 14:53:34 [info] : Usage updated: 303 GB. Next update at 10:53:22 PM,
2022-07-12 22:53:34 [info] : Usage updated: 348 GB. Next update at 6:53:22 AM,
2022-07-13 06:53:57 [error] : TimeoutError: waiting for selector `#passwd` failed: timeout 30000ms exceeded. Next update at 2:53:22 PM`

**Comment by zachowj** [comment]
I have my update set to 20 mins and it has been working fine. Yes, there are some TimeoutErrors here and there but it succeeds most of the time.

**Comment by janssenjones** [comment]
Thanks for the feedback.  Glad to know it's still working for others.  I set this up on both Docker and Kubernetes, and haven't had either of them work since July 3.  I'll try running this from a different IP just to see if it changes anything.

**Comment by janssenjones** [comment]
I've started trying to test more in my Docker instance.  I had an old pwsuffix and cookies.json that I've cleared and hardcoded in with the new pass.  I also added a pageTimeout of 60 to the config.yml since I thought maybe it was a timeout issue, but it doesn't seem to respect that interval, and always reports that it times out after 30 seconds.

I'm intermittently seeing a different issue now, which is a crash on the security check, which is maybe now my main issue:

xfinity    | 2022-07-14 10:23:36 [debug] : Login redirects: 3
xfinity    | 2022-07-14 10:23:36 [debug] : Logging in
xfinity    | 2022-07-14 10:23:41 [debug] : Page Title: Security Check
xfinity    | 2022-07-14 10:23:41 [info] : Clicking "Ask me later" for security check
xfinity    | /home/node/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:217
xfinity    |             this._callbacks.set(id, { resolve, reject, error: new Error(), method });
xfinity    |                                                               ^
xfinity    |
xfinity    | Error: Protocol error (Runtime.callFunctionOn): Target closed.
xfinity    |     at /home/node/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:217:63
xfinity    |     at new Promise (<anonymous>)
xfinity    |     at CDPSession.send (/home/node/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:216:16)
xfinity    |     at ExecutionContext._evaluateInternal (/home/node/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:204:50)
xfinity    |     at ExecutionContext.evaluateHandle (/home/node/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:155:21)
xfinity    |     at WaitTask.rerun (/home/node/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/DOMWorld.js:536:37)
xfinity    |     at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by janssenjones** [comment]
Yeah, logging in and manually dealing with those pages was required. It looks like the container can't handle an updated 2FA prompt page.

My steps were to login, add 2FA, and then immediately remove 2FA (there's not actually an "Ask me later" on that screen, which is maybe what changed, and the container code can't handle the new page that's forcing 2FA).

After adding and removing 2FA, I relaunched the container and got the timeout waiting for passwd.  I instantly killed and recreated the container, and it successfully went through...

Whew...
